### PR TITLE
fix: Ensure InputField value reflects state updates

### PR DESCRIPTION
**Pull request by zhibek**
**NOTE: This is a draft PR. I don't expect this to be merged directly, because `InputField` is a core component that hasn't changed for a long time.**

### CODE REVIEW

**Comment by zhibek** [comment]
I've been investigating why `PostcodeLookup` doesn't update `postcode` formatting to match the selected address (based on the example on NOTV where `G73 3 LX` caused problems with `ERP` validation. This postcode (`G73 3 LX`) *is* handled by postcode lookup and a valid address is found. However, the whitespace causes `ERP` validation to fail.

This code code shows that `PostcodeLookup` component *should* update the postcode field with the correct whitespace when an address is selected (but it's not happening):
https://github.com/comicrelief/storybook/blob/master/src/components/PostcodeLookup/PostcodeLookup.js#L284-L288

I traced the problem through to `InputField`, where the `value` set on this field in a state update, isn't reflected to the `<input>` element inside it. Because of this, updating `value` state on `InputField` doesn't work correctly.

**Comment by AndyEPhipps** [comment]
All makes sense to me, @zhibek! I'll test this within Donate locally

**Comment by AndyEPhipps** [comment]
I'm getting some unrelated Cypress failures when I run this PR **_or_** the most recent version of Storybook in Donate locally, so I'm gonna update and release this PR as a new version just so I'm able to fix everything in one place, verified by the pipeline too.

**Comment by AndyEPhipps** [comment]
The Workflow test failures here are down to a messed-up image regression tests - I've tried and failed many a time to figure out why the committed image and the test-produced images are all of a different browser resolution (so all the tests fail), eventually gave up and have just been force-merging after manually checking effected work; will get round to removing it from the Workflow tests eventually.

**Review by AndyEPhipps — APPROVED** [review]

**Pull request merged**
