### PR TITLE
#71 Add DefinePlugin to attempt to create production-minimised build

### PR DESCRIPTION
**Pull request by ayanozturk**

### CODE REVIEW

**Comment by adamclark-dev** [comment]
@ayanozturk do we need to create a production build of storybook, should this not be done by the project that is importing storybook. Not a major issue either way...

**Comment by ayanozturk** [comment]
@adamclark-dev I was thinking that when we reference and import storybook in the project, it is already built during publishing and release.

**Comment by adamclark-dev** [comment]
@ayan makes sense

**Comment by ayanozturk** [comment]
@adamclark-dev I tested this on my local and it worked. I think it is ready to be merged.

**Comment by twhiteley** [comment]
➤ Tom Whiteley commented:

Transition made by Unito

**Pull request merged**
