### PR TITLE
feat: Added toggle to marketing consent component

### PR DESCRIPTION
**Pull request by s-barrah**
feat: Added toggle to marketing consent component

### CODE REVIEW

**Comment by Heleen-cr** [comment]
@s-barrah I can't remember if we verified with Caroline in the end whether this is the functionality we want. Was it ok?

**Comment by s-barrah** [comment]
> @s-barrah I can't remember if we verified with Caroline in the end whether this is the functionality we want. Was it ok?

I don't think we have. We can leave it for now.

**Comment by AndyEPhipps** [comment]
@s-barrah - I'm getting nudged by the Panda to review this.. is still this still needed?

**Comment by s-barrah** [comment]
> @s-barrah - I'm getting nudged by the Panda to review this.. is still this still needed?

Probably not

**Comment by AndyEPhipps** [comment]
Okeydokey, will let you close it once you're sure if thats cool ✌️

**Pull request closed without merging**
