### PR TITLE
1 - updating readme

### PR DESCRIPTION
**Pull request by gusliedke**
add install as dependency instructions

### CODE REVIEW

**Comment by gusliedke** [comment]
@adamclark-dev can you update with the instructions to include it in a project, like we did for CR?

**Comment by pvhee** [comment]
@gusliedke can you update so we can merge this in?

**Comment by gusliedke** [comment]
@pvhee we need to add the instructions on how to use it

**Comment by twhiteley** [comment]
➤ Tom Whiteley commented:

Transition made by Unito

**Pull request merged**
